fix uuid generator function error
error driven command: npx prisma migrate dev --name add-cascade-reference-to-invoices-and-customers

```
Error: P3006

Migration `0_init` failed to apply cleanly to the shadow database.
Error:
ERROR: function uuid_generate_v4() does not exist
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
   0: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:276
```